Update docker-app-deployment.yml

diff --git a/.github/workflows/docker-app-deployment.yml b/.github/workflows/docker-app-deployment.yml
--- a/.github/workflows/docker-app-deployment.yml
+++ b/.github/workflows/docker-app-deployment.yml
@@ -36,19 +36,19 @@ jobs:
           role-to-assume: arn:aws:iam::565393030819:role/Github-Actions-role
           aws-region: ${{ secrets.AWS_REGION }}
 
-      # - name: Wait for ECR repository to exist
-      #   run: |
-      #     echo "Checking for ECR repository..."
-      #     for i in $(seq 1 20); do
-      #       if aws ecr describe-repositories --repository-names my-app --region us-east-2 2>/dev/null; then
-      #         echo "ECR repository found — continuing"
-      #         exit 0
-      #       fi
-      #       echo "Attempt $i/20 — ECR not ready yet, waiting 30 seconds..."
-      #       sleep 30
-      #     done
-      #     echo "ECR repository not found after 10 minutes — exiting"
-      #   exit 1
+      - name: Wait for ECR repository to exist
+        run: |
+          echo "Checking for ECR repository..."
+          for i in $(seq 1 20); do
+            if aws ecr describe-repositories --repository-names my-app --region us-east-2 2>/dev/null; then
+              echo "ECR repository found — continuing"
+              exit 0
+            fi
+            echo "Attempt $i/20 — ECR not ready yet, waiting 30 seconds..."
+            sleep 30
+          done
+          echo "ECR repository not found after 10 minutes — exiting"
+          exit 1
 
       # GitHub Actions assumes AWS IAM role using OIDC (no static AWS keys)
       - name: Login to Amazon ECR
